### ISSUE TITLE
cuda-python backend

### ISSUE THREAD

**Issue by benvanwerkhoven** [KernelTuner/kernel_tuner#144]
Nvidia's official Python bindings for CUDA: https://github.com/NVIDIA/cuda-python are in the end the most future-proof Python bindings for Kernel Tuner to use. @isazi already started working on a backend for Kernel Tuner based on these bindings. 

I wanted to make this issue to have a place to collect ideas and discuss features of this backend. 

- One thing that is currently not working all that well with CuPy and PyCuda is properly detecting skipable errors. These are errors that can be expected during tuning and that Kernel Tuner skips over automatically without breaking. However, it seems the runtime and compiler error messages that cupy and pycuda return are no longer specific enough to distinguish between unexpected errors and errors that we would like to skip. It would be great if we could get this correctly for the cuda-python backend.

**Comment by isazi** [comment]
Do you want that I have a look at error messages, or should we close this issue?

**Comment by benvanwerkhoven** [comment]
I think we can leave the error messages as they are for now. I think the main issue is that cupy provides no way to get good error messages. I've recently made a few small changes to the cuda-python backend to extract the compiler error if there is any. I'll close the issue.
