### ISSUE TITLE
HIP Backend

### ISSUE THREAD

**Issue by benvanwerkhoven** [KernelTuner/kernel_tuner#152]
We are planning to develop a HIP backend for Kernel Tuner, to be able to tune kernels written for HIP just as easily as CUDA kernels.

One issue with creating a HIP backend earlier was there were no Python bindings for HIP, but there seems to be one now: https://github.com/jatinx/PyHIP

**Comment by isazi** [comment]
Nice, but I have the feeling the python bindings are not really maintained anymore, nor much used, and that may be an issue in the future.

**Comment by benvanwerkhoven** [comment]
Indeed, it is mentioned in the readme of that project that contributions are welcome. The last commit is from two months ago, so not that long ago. I was thinking that we may be able to contribute a bit to the bindings as well if needed. Having a HIP Backend is important enough in my opinion.

**Comment by jatinx** [comment]
Hey Folks, I am the author of those binding.

I am still active and use those bindings for some personal use. I won't change it till I find some personal use, but if you folks are interested I'll be happy to add new stuff :)

**Comment by benvanwerkhoven** [comment]
The HIP backend has been merged! So we can close this issue
