### ISSUE TITLE
redesigning the readme

### ISSUE THREAD

**Issue by benvanwerkhoven** [KernelTuner/kernel_tuner#190]
I'd like to give the README a big update at some point, including:

- [x] logo designed by Stijn
- [x] vastly reduce amount of text, just point to documentation
- [ ] more about performance and productivity impact of auto-tuning
- [ ] potential energy gains using auto-tuning with Kernel Tuner
- [x] bunch of logos of institutes where Kernel Tuner is used in production
- [ ] pointers to related tools: Tutorial, Kernel Launcher, Kernel Float, Dashboard
- [ ] listing the Kernel Tuner Developers team as core developers
- [x] categorize the 'please cite these papers' section

Any other suggestions?

**Comment by stijnh** [comment]
Some suggestions:

* Short list of features at the top (like 4-5 bullets)
* Table showing supported backends
* List of FAQ (could also be in documentation)
* Section on what to do if you run into a bug/issue/feature request.

**Comment by stijnh** [comment]
This has been resolved by PR #231
