### ISSUE TITLE
C compiler version parsing error

### ISSUE THREAD

**Issue by isazi** [KernelTuner/kernel_tuner#193]
In file `kernel_tuner/backends/c.py` the way that `cc_version` is computed only works for `gcc`/`g++` and not for e.g. `nvc++` or other compilers.

**Comment by benvanwerkhoven** [comment]
Just checking, this issue will be fixed by pull request #197 right?

**Comment by isazi** [comment]
Yes, for compilers including gcc, nvc, nvcc, nvc++, nvfortran.

**Comment by isazi** [comment]
This should be fixed now.
