### ISSUE TITLE
Remove dependence on `OrderedDict`?

### ISSUE THREAD

**Issue by loostrum** [KernelTuner/kernel_tuner#209]
Some parts of kernel tuner require an `OrderedDict`, however as of Python 3.7 the standard `dict` is guaranteed to be insertion ordered. If this is the only reason `OrderedDict` was required, perhaps the requirement could be removed to simplify the interface.

**Comment by isazi** [comment]
I believe that @fjwillemsen was going to do that, after we are done with the Kernel Tuner tutorial at RSECon23 in September.

**Comment by fjwillemsen** [comment]
Yes, I can do this!

**Comment by loostrum** [comment]
Great!

**Comment by fjwillemsen** [comment]
I've just resolved this issue in the commit linked above, which is part of a larger pull request.
