### ISSUE TITLE
Passing cupy arrays to the compiler backend

### ISSUE THREAD

**Issue by bouweandela** [KernelTuner/kernel_tuner#224]
In a project that I'm working on, it would be useful to be able to create the arrays with cupy and then pass them to the C++ code (that contains a mix of cuda library, e.g. cufft, calls and custom kernels). Is this a feature that is of interest? I got it to work locally, so I could make a pull request if you're interested.

At the moment, this fails on this check and missing support further on in the same function:
https://github.com/KernelTuner/kernel_tuner/blob/08fb58eed26b12fd8da5235298308e2e4e019ede/kernel_tuner/backends/compiler.py#L115

**Comment by benvanwerkhoven** [comment]
Hi Bouwe! I think I've looked at this in the past, but back then I thought it was not possible to recover the underlying pointer to device memory from a cupy array object. I'm very happy to hear that you got this to work! I think this could be a very nice addition to the compiler backend to support this as well.
