### ISSUE TITLE
API documentation is broken

### ISSUE THREAD

**Issue by loostrum** [KernelTuner/kernel_tuner#233]
[this](https://kerneltuner.github.io/kernel_tuner/stable/user-api.html) page should contain API documentation, but it is empty.

**Comment by benvanwerkhoven** [comment]
Hi @loostrum! Thanks for reporting! No clue how this could have happened. In the meantime, please use https://kerneltuner.github.io/kernel_tuner/0.4.5/user-api.html

**Comment by loostrum** [comment]
Thanks for the link! CI looked all green so I'm not sure what happened either.
